### ISSUE TITLE
Commands to use with `gds-cli` don't match usage statements or `--help`.

### ISSUE THREAD

**Issue by issyl0** [alphagov/govuk-connect#44]
This was reported in the most recent (Summer 2020) developer tools survey. The report didn't have much context. I've done some digging and hope to expand upon the title such that it can be solved to make more sense to users.

----

To start things off:

```shell
➜ govuk-connect --version
0.3.0
➜ gds --version
gds version v2.19.0
➜ gds govuk connect --version # for the avoidance of doubt that it's using the same (Homebrew-installed) binary.
0.3.0
```

----

The problem:

```shell
➜ gds govuk connect --help
Usage: govuk-connect TYPE TARGET [options]
    -e, --environment ENVIRONMENT    Select which environment to connect to
        --hosting-and-environment-from-alert-url URL
                                     Select which environment to connect to based on the URL provided.
    -p, --port-forward SERVICE       Connect to a remote port
    -v, --verbose                    Enable more detailed logging
    -h, --help                       Prints usage information and examples
    -V, --version                    Prints version information
```

I think it's that `govuk-connect ...` usage line that people are complaining about - the fact that it doesn't say `gds govuk connect`, because all we're doing is wrapping `govuk-connect` up in another convenient command so that people don't have to switch between tools.

Another thing which @kevindew  pointed out was that the usage string's `TYPE TARGET [options]` stipulation is reversed in the examples.

I would also like to move the "EXAMPLES" from the `--help` text up to the top (below the usage statement). I don't know if people read `--help` vs. the (non-existent) docs, but putting common tasks at the top will probably help people.

----

Maybe I'll get time to work on this soon, maybe I won't. But posting it here in case anyone else wants to have a go. If anyone finds anything else that's wrong, add it in!

**Comment by cbaines** [comment]
> I think it's that `govuk-connect ...` usage line that people are complaining about - the fact that it doesn't say `gds govuk connect`, because all we're doing is wrapping `govuk-connect` up in another convenient command so that people don't have to switch between tools.

Note that the ability to call govuk connect from the gds-cli was just intended to help those in RE GOV.UK that also needed to SSH in to machines. Personally, I still type "govuk connect ..." as this is shorter.

Although, this was being planned out at a time when it wasn't possible for those on GOV.UK to do things like assume roles with the gds-cli, so the ideal level of integration might have changed since the push at the moment seems to be to depend more on AWS services.
