### ISSUE TITLE
Using the USER env var method may cause problems

### ISSUE THREAD

**Issue by KludgeKML** [alphagov/govuk-connect#72]
If IT set up your username to have dots in it (as they have on my machine), but. your integration SSH name has no dots in it (as seems to be the mode), you'll have a clash if you try to set the env var used here:

https://github.com/alphagov/govuk-connect/blob/main/lib/govuk_connect/cli.rb#L233

USER is used by (eg) homebrew, so if my machine name is keith.lawrence, my ssh name keithlawrence, setting USER to keith.lawrence (or leaving it unset) will cause govuk-connect to fail, but setting it to keithlawrence will cause brew to fail.

You can fix this by using the config.yaml method, but that seems like it's not being used a lot? (there's no documentation about where it is, and it turns out to be the very generically named ~/.config/config.yaml)

**Comment by ollietreend** [comment]
For what it's worth, I have the same problem because I'm on a BYOD which has a different username.

My hacky workaround is to include this in my `~/.zshrc`:

```
alias gds="USER=mygovukusername gds"
```

So the `USER` environment variable automatically gets prepended when I run `gds` commands.

However, the proposal from @ChrisBAshton is of course a much nicer way to solve it 👍🏻

**Comment by ollietreend** [comment]
@KludgeKML one 'quick' way around the `.` period problem is to substitute it for a `-` dash using [bash parameter expansion](https://stackabuse.com/guide-to-parameter-expansion-in-bash/#replacingapartofavariablevariablepatternreplacement)

```
$ echo ${USER/./-}
ollie-treend
```

**Comment by KludgeKML** [comment]
@ollietreend - Ah, nice. I've just checked that's also good on zsh (since that's the default on OSX, and I and presumably some others will still be on it). I'll put a PR into special-route-publisher to add that to the documentation.

**Comment by sengi** [comment]
Repo being archived now that we're no longer running Puppet or bastion hosts or SSH etc. etc.
